feat(all contracts): update main to cosmwasm 1.0.0
astroport-fi/astroport-core pull request #276
Opened 2022-06-08 07:43 UTC by P-Yevhenii

2022-06-08 14:27 UTC, epanchee requested changes

2022-06-08 15:57 UTC, P-Yevhenii commented on contracts/tokenomics/xastro_token/src/contract.rs
> +        .map(|addr| addr.map(String::from))
Cool! Thanks

2022-06-08 16:00 UTC, P-Yevhenii commented on packages/astroport/src/math.rs
> +pub fn decimal2decimal256(dec_value: Decimal) -> StdResult<Decimal256> {
Let it be, I don't mind

2022-06-08 16:08 UTC, epanchee commented on contracts/tokenomics/maker/tests/integration.rs
> -        let governance_amount =
This todo still needs to be added

2022-06-09 10:24 UTC, ShadoySV approved these changes

2022-06-09 10:24 UTC, ShadoySV commented on contracts/tokenomics/generator_proxy_to_mirror/src/contract.rs
> +            // let reward_infos = res.reward_infos;
Mark this with TODO too

2022-06-10 10:32 UTC, maksk7 approved these changes
Approved, but fix conflicts and contracts compilement

2022-06-15 12:55 UTC, merged