feat(generator, factory): updated logic according to the last audit
astroport-fi/astroport-core pull request #288
Opened 2022-07-15 06:40 UTC by P-Yevhenii

2022-07-18 10:50 UTC, epanchee commented on contracts/tokenomics/generator/src/contract.rs
> +    // let reward_msg = build_claim_pools_asset_reward_messages(
Mark this with // TODO: resolve when bLuna is deployed on Terra2

2022-07-18 10:50 UTC, epanchee commented on contracts/tokenomics/generator/src/contract.rs
> +            "1.1.0" => {
I guess migrations for 1.2.0 and 1.3.0 can be removed

2022-07-18 10:50 UTC, epanchee commented on contracts/tokenomics/generator/tests/integration.rs
> -// TODO: Mirror protocol does not support Terra2 and cosmwasm-1.0 respectively.
Keep these todos

2022-07-18 10:50 UTC, epanchee commented on packages/astroport/src/lib.rs
> +pub mod pair_stable_bluna;
Move this one the previous place

2022-07-18 10:50 UTC, epanchee commented on scripts/build_release.sh
> +#!/usr/bin/env bash
Give execution rights to this script

2022-07-18 11:07 UTC, ShadoySV requested changes

2022-07-18 15:29 UTC, epanchee approved these changes

2022-07-19 07:29 UTC, ShadoySV approved these changes

2022-07-19 07:31 UTC, merged