feat(generator): boosties v2
astroport-fi/astroport-core pull request #293
Opened 2022-08-08 13:18 UTC by P-Yevhenii

2022-08-12 08:25 UTC, ShadoySV requested changes

2022-08-12 08:25 UTC, ShadoySV commented on contracts/tokenomics/generator/src/migration.rs
> +        voting_escrow_delegation: None,
Set it from ```MigrateMsg```. The same below

2022-08-12 08:25 UTC, ShadoySV commented on contracts/tokenomics/generator/src/state.rs
> +        if let Some(voting_delegation) = &cfg.voting_escrow_delegation {
Use original voting power if the voting escrow delegation contract isn't set

2022-08-15 07:33 UTC, ShadoySV approved these changes

2022-08-15 10:43 UTC, epanchee approved these changes

2022-08-15 10:43 UTC, epanchee commented on contracts/tokenomics/generator/src/contract.rs
> +            Option::from(addr_validate_to_lower(deps.api, &voting_escrow_delegation)?);
```suggestion
            Some(addr_validate_to_lower(deps.api, &voting_escrow_delegation)?);
```

2022-08-15 10:43 UTC, epanchee commented on contracts/tokenomics/generator/src/contract.rs
> +        config.voting_escrow = Option::from(addr_validate_to_lower(deps.api, &voting_escrow)?);
```suggestion
        config.voting_escrow = Some(addr_validate_to_lower(deps.api, &voting_escrow)?);
```

2022-08-15 14:35 UTC, ShadoySV requested changes
Dependencies with ```feat/escrow_delegation``` should be replaced with ```main``` when them is merged

2022-08-17 14:39 UTC, ShadoySV approved these changes

2022-08-17 14:39 UTC, merged