fix(pair): added initial minting
astroport-fi/astroport-core pull request #301
Opened 2022-09-06 05:30 UTC by P-Yevhenii

2022-09-07 06:33 UTC, ShadoySV approved these changes

2022-09-08 08:54 UTC, epanchee requested changes

2022-09-08 08:54 UTC, epanchee commented on contracts/pair/src/contract.rs
> +        // share is cannot be zero after subtracted minimum liquidity amount
```suggestion
        // share cannot become zero after minimum liquidity subtraction
```

2022-09-08 08:54 UTC, epanchee commented on contracts/pair/src/error.rs
> +    #[error("Insufficient amount of liquidity to initially provide")]
```suggestion
    #[error("Initial liquidity must be more than {}", MINIMUM_LIQUIDITY_AMOUNT)]
```

2022-09-08 08:54 UTC, epanchee commented on contracts/periphery/oracle/tests/integration.rs
> +    // try to provide less then 1000
Why do we place pair contract logic integration tests within oracle crate?
I suggest to move this test under pair crate.

2022-09-09 09:03 UTC, epanchee approved these changes

2022-09-09 09:10 UTC, ShadoySV approved these changes

2022-09-09 09:10 UTC, merged