feat(maker): choose pool with the best execution when swapping fee tokens
astroport-fi/astroport-core pull request #304
Opened 2022-09-14 16:40 UTC by epanchee

2022-09-16 14:29 UTC, ShadoySV requested changes
Let's use simulated return amounts instead of SWAP_SIMULATION_AMOUNT

2022-09-19 11:07 UTC, ShadoySV requested changes

2022-09-19 11:20 UTC, epanchee commented on contracts/tokenomics/maker/src/utils.rs
> +        _ => {
Old pairs which were created before factory migration (with multipool support) might not have record in ROUTES state. Thus here may appear an error.

2022-09-19 14:47 UTC, ShadoySV commented on contracts/tokenomics/maker/src/utils.rs
> +        _ => {
Routes are created on Factory migration for all registered pairs

2022-09-20 13:09 UTC, ShadoySV approved these changes

2022-09-22 07:32 UTC, P-Yevhenii approved these changes

2022-09-22 07:38 UTC, merged