feat(pair stable): query accumulate prices fixed
astroport-fi/astroport-core pull request #307
Opened 2022-09-20 08:50 UTC by P-Yevhenii

2022-09-20 09:33 UTC, epanchee approved these changes

2022-09-21 13:11 UTC, ShadoySV requested changes
Let's return accumulate_prices's errors, as it is done for XYK [pair](https://github.com/astroport-fi/astroport/blob/b47f5ad5fa546b0e176401181fb31c5ca0412d37/contracts/pair/src/contract.rs#L435), everywhere instead of checking that it is ok (line 581, 677, 947). The same approach for line 1262.
Also we need this for #308

2022-09-23 14:40 UTC, epanchee requested changes

2022-09-23 14:40 UTC, epanchee commented on contracts/pair_stable/tests/3pool_tests.rs
> -                assert!(!price[0].2.is_zero());
You can not remove this line. This is the main line in the test.

2022-09-27 08:19 UTC, ShadoySV approved these changes

2022-10-03 08:14 UTC, epanchee approved these changes

2022-10-03 11:42 UTC, merged