feat(all SCs): update to cosmwasm 1.1
astroport-fi/astroport-core pull request #312
Opened 2022-09-29 23:00 UTC by P-Yevhenii

2022-10-03 13:23 UTC, epanchee commented
Consider my suggestions from https://github.com/astroport-fi/astroport-core/pull/311

2022-10-04 07:03 UTC, ShadoySV requested changes

2022-10-05 07:32 UTC, ShadoySV approved these changes

2022-10-05 11:50 UTC, epanchee approved these changes

2022-10-05 12:08 UTC, merged