Feat(new pool type): concentrated liquidity pool
astroport-fi/astroport-core pull request #325
Opened 2022-11-24 11:36 UTC by epanchee

2022-12-30 08:56 UTC, ShadoySV requested changes

2023-01-05 10:54 UTC, ShadoySV requested changes

2023-01-05 10:54 UTC, ShadoySV commented on contracts/pair_concentrated/src/queries.rs
> +            initial_price_scale: price_scale,
Maybe rename the field price_scale?

2023-01-09 15:03 UTC, epanchee commented on contracts/pair_concentrated/src/queries.rs
> +            initial_price_scale: price_scale,
Ok

2023-01-09 15:05 UTC, epanchee commented on contracts/pair_concentrated/src/utils.rs
> +        // overflow is possible if time_elapsed > 340282366920939 seconds ~ 10790283 years
This comment is not related to wrapping_* operations, but explains why I convert Decimal256 to Uint128 and use .unwrap() here.

2023-01-09 15:08 UTC, epanchee commented on contracts/pair_concentrated/src/utils.rs
> +    let fee_rate = config.pool_params.fee(&ixs_for_fees);
Added multistage fee forecasting. Works nice besides it consumes more gas because of calc_y(). But this is query, this should not matter.

2023-01-10 10:09 UTC, epanchee commented on contracts/pair_concentrated/src/utils.rs
> +    let last_price = config.pool_state.price_state.last_price;
That's true. Fixed

2023-01-10 10:11 UTC, epanchee commented on contracts/pair_concentrated/README.md
> +    "receiver": "terra..."
Slippage tolerance is unused in the concentrated liquidity pair https://github.com/astroport-fi/astroport-core/blob/dd6134cef46f2ea7fcf00a99de5cdf0f341be341/contracts/pair_concentrated/src/contract.rs#L361

2023-01-10 10:26 UTC, epanchee commented on contracts/pair_concentrated/src/contract.rs
> +    assets: Vec<Asset>,
That's true. Added default serve desiralization so if used omit an "assets" fields and will be deserialized into empty vector.

2023-01-10 10:27 UTC, epanchee commented on contracts/pair_concentrated/src/contract.rs
> +    }
Done

2023-01-10 13:30 UTC, P-Yevhenii approved these changes

2023-01-11 17:38 UTC, ShadoySV requested changes

2023-01-11 17:38 UTC, ShadoySV commented on contracts/pair_concentrated/src/utils.rs
> +    let fee_rate = config.pool_params.fee(&ixs_for_fees);
Fee rate can still be greater

2023-01-12 11:47 UTC, epanchee commented on contracts/pair_concentrated/src/utils.rs
> +    let fee_rate = config.pool_params.fee(&ixs_for_fees);
True. Applied max fees in reverse swap query

2023-01-12 13:50 UTC, epanchee commented on contracts/pair_concentrated/src/queries.rs
> +    }
True. Fixed

2023-01-13 12:03 UTC, ShadoySV commented on contracts/pair_concentrated/src/queries.rs
> +    }
It is still not fixed. `offer_amount` should be `Decimal::one`

2023-01-13 12:14 UTC, ShadoySV requested changes

2023-01-13 12:14 UTC, ShadoySV commented on contracts/pair_concentrated/src/queries.rs
> +        offer_amount / swap_result.dy + swap_result.total_fee,
```suggestion
        offer_amount / (swap_result.dy + swap_result.total_fee),
```

2023-01-16 10:18 UTC, epanchee commented on contracts/pair_concentrated/src/queries.rs
> +    }
Thank you. Added

2023-01-24 08:54 UTC, ShadoySV requested changes

2023-01-24 11:36 UTC, ShadoySV approved these changes

2023-01-24 14:25 UTC, merged