Feat(stableswap): revert stableswap implementation
astroport-fi/astroport-core pull request #329
Opened 2022-12-23 12:21 UTC by epanchee

2023-01-31 12:46 UTC, ShadoySV requested changes

2023-01-31 12:46 UTC, ShadoySV commented on contracts/pair_stable/src/contract.rs
> +        ask_precision,
```suggestion
        config.greatest_precision,
```

2023-02-07 07:03 UTC, ShadoySV approved these changes

2023-02-08 08:24 UTC, P-Yevhenii approved these changes

2023-02-09 08:40 UTC, merged